// <auto-generated />
using System;
using LeaderboardAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LeaderboardAPI.Migrations
{
    [DbContext(typeof(LeaderboardContext))]
    [Migration("20200929162513_FixMigration")]
    partial class FixMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LeaderboardModel.Level", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("levels");
                });

            modelBuilder.Entity("LeaderboardModel.Player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("country_code")
                        .HasColumnType("integer");

                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("LeaderboardModel.Score", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("high_score")
                        .HasColumnType("integer");

                    b.Property<int?>("levelid")
                        .HasColumnType("integer");

                    b.Property<int?>("playerid")
                        .HasColumnType("integer");

                    b.Property<int>("time_in_seconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("time_stamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("levelid");

                    b.HasIndex("playerid");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("LeaderboardModel.Score", b =>
                {
                    b.HasOne("LeaderboardModel.Level", "level")
                        .WithMany()
                        .HasForeignKey("levelid");

                    b.HasOne("LeaderboardModel.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerid");
                });
#pragma warning restore 612, 618
        }
    }
}
